name: MythicDropRefactored
version: '4.1.1'
main: fr.elias.mythicDrop.MythicDrop
api-version: '1.20'
author: Elias
depend: [MythicMobs]
softdepend: [LuckPerms]
load: STARTUP
# Commands for the plugin
commands:
  mythicdrop:
    description: "Base command for MythicDrop plugin"
    usage: "/mythicdrop reload"
    permission: mythicdrop.reload
    permission-message: "You do not have permission to execute this command."

# Permissions for the plugin
permissions:
  mythicdrop.reload:
    description: "Allows reloading the MythicDrop configuration"
    default: op
